### ISSUE TITLE
Return the UMAP model?

### ISSUE THREAD

**Issue by biobenkj** [Alanocallaghan/densvis#3]
Hi Alan, thanks again for all your work on densvis! I think something that I'd love to be able to do is pass a SingleCellExperiment object to densvis and be able to return the model for embedding new data, etc. Totally happy to fork and make a PR on this but wanted to check and see if you already have this rolling. Thanks again!

**Comment by alanocallaghan** [comment]
This is a bit tricky with basilisk as return objects need to be pure R, see 3.4 here: https://bioconductor.org/packages/devel/bioc/vignettes/basilisk/inst/doc/motivation.html

You can in principle convert python objects into R objects, and then directly call python constructors on those R objects to recreate the python objects. If you can point to an example of the python code you'd like to wrap I can see if it's doable. I did something similar for snifter

An alternative would be to have a non-basilisk (ie non-conda) portion of the package that just directly uses reticulate, but there are some issues there too. In particular reticulate seems to install everything into the same `r-reticulate` conda environment when used in a package. Mixed versions of R and python packages sounds like development hell in its purest form so I'd like to avoid that https://rstudio.github.io/reticulate/articles/package.html

**Comment by biobenkj** [comment]
That does sound like the lowest ring of development hell. I will look a little more and see if there is some python code that might be worth wrapping up. Thanks!

**Comment by biobenkj** [comment]
Yep, I've done a little digging and this is not pleasant. Closing for now and happy to re-open if I find a work around. Thanks!
