### ISSUE TITLE
error: n_neighbors is not an integer vector

### ISSUE THREAD

**Issue by Thapeachydude** [Alanocallaghan/densvis#9]
Hi, 

is the number of nearest neighbors still a parameter? If I try to run the data from the vignette with for example n = 15, I get the following error: 

```
densmap(data[, 1:2], dens_frac = 0.5, dens_lambda = 0.5, n_neighbors = 15)
Error: n_neighbors is not an integer vector
```

Any insights would be much appreciated. : )

**Comment by alanocallaghan** [comment]
`densmap(data[, 1:2], dens_frac = 0.5, dens_lambda = 0.5, n_neighbors = 15L)` should work

**Comment by alanocallaghan** [comment]
The package was doing overly strict checking, because when calling python from R, python would recognise `15` as a floating point number and `15L` as an integer. I've relaxed these checks, so now if you pass in `15` the package will internally convert into an integer.

Note this was the case for `n_components`, `n_neighbors`, `n_epochs`, `local_connectivity`, `negative_sample_rate`, and `random_state`

**Comment by Thapeachydude** [comment]
Hi, 

thanks for the crazy quick reply. 
Unfortunately, there seems to be another issue (uninstalled the old version from Bioconductor and installed again from github). 

```
fit1 <- densmap(data[, 1:2], dens_frac = 0.5, dens_lambda = 0.5)
Error: assert_that: assertion must return a logical value
```

On another note: is there a way to parallelize this? i.e. through Biocparallels?

**Comment by alanocallaghan** [comment]
Ah sorry yeah, mistake in the code for int checking.

densmap leans on the python umap library, which apparently has multi-CPU support, though I don't know the details beyond that. BiocParallel wouldn't be useful unless you want to calculate multiple UMAPs on different threads

https://umap-learn.readthedocs.io/en/latest/faq.html#is-there-gpu-or-multicore-cpu-support

**Comment by Thapeachydude** [comment]
That seems to have done the trick. 

Curiouse, scran has a UMAP implementation that is able to multi-thread via BiocParallel, but maybe its running an R implementation (I thought its also running python under the hood9. But thanks. 

Final follow-up: 
The densmap looks something like this. What parameter is best to reduce the extreme values? i.e. to avoid these extreme x and y coordinates of only a handful of cells. Normal UMAP as comparison.
Densmap
![grafik](https://github.com/user-attachments/assets/6360a7b1-388b-4d63-b289-825ad8c0780c)

UMAP
![grafik](https://github.com/user-attachments/assets/6b22440f-8b98-45b5-9757-5190bcfb289a)

**Comment by alanocallaghan** [comment]
> Curiouse, scran has a UMAP implementation that is able to multi-thread via BiocParallel, but maybe its running an R implementation (I thought its also running python under the hood9. But thanks.

I think you mean scater? That's as far as I know only used for the KNN calculation. And yeah it's using `uwot::umap` not python's umap.

https://github.com/alanocallaghan/scater/blob/d14427e6778fb1c8b6f4d2ff590b6869e7efbd3a/R/runUMAP.R#L85-L90

>  The densmap looks something like this. What parameter is best to reduce the extreme values? i.e. to avoid these extreme x and y coordinates of only a handful of cells. Normal UMAP as comparison.

Not a clue really, I've not really played with densmap in a while but I don't ever remember seeing extreme values like that. I'd considering first setting the dens_frac to zero to see if it's a general problem with these UMAP settings on these data, then adjust any repulsion settings (the [UMAP docs](https://umap-learn.readthedocs.io/en/latest/parameters.html) are pretty good), then try to adjust convergence criteria

**Comment by Thapeachydude** [comment]
Ok, thanks. I'll play a bit around with it. : )
